### PR TITLE
minor: fix docs around authenticating provider with environment variables

### PR DESCRIPTION
**Pull request by youcandanch**
Summary
-------

Spots in the documentation are inconsistent about whether to use PREFECT_API_KEY or PREFECT_CLOUD_API_KEY when passing the provider authentication config via environment variables. This PR consolidates documentation around this to use PREFECT_API_KEY, which is what the provider is currently looking for [here](https://github.com/PrefectHQ/terraform-provider-prefect/blob/a5ca0d39fd2ec3b378525d94f217114fc38580b7/internal/provider/provider.go#L146).

### CODE REVIEW

**Comment by parkedwards** [comment]
ah thanks for the PR @youcandanch -- you are correct, it should be the other way around. the correct env var is `PREFECT_API_KEY`, and it looks like we've mistakenly documented this var as `PREFECT_CLOUD_API_KEY`

if you could update all doc references to `PREFECT_API_KEY`, that would be amazing

**Comment by youcandanch** [comment]
@parkedwards yeaaaaah kinda figured once I changed it and the acceptance tests immediately gave me the virtual bird. Give me a sec and I'll update!

**Comment by youcandanch** [comment]
Acceptance tests dependent on https://github.com/PrefectHQ/terraform-provider-prefect/pull/158, another casualty of the underscore war.

**Review by parkedwards — APPROVED** [review]
ill fix the labeler and docs workflow jobs, they're not being permitted bc it's coming from an external fork. thanks for submitting!

**Pull request merged**
